version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:4.10.0
    ports:
      - "4444:4444"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  chrome:
    image: selenium/node-chrome:4.10.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 5

  firefox:
    image: selenium/node-firefox:4.10.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 5

  edge:
    image: selenium/node-edge:4.10.0
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 5
